name: Generate Documentation
on:
  push:
    paths:
      - 'main.md'
      - 'chart.md'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate ARCHITECTURE.md
        run: |
          #!/bin/bash
          # Initialize ARCHITECTURE.md
          : > ARCHITECTURE.md
          
          # Process main.md line by line
          while read -r line; do
            if [[ "$line" == *"@import \"chart.md\""* ]]; then
              # Add newline before mermaid block
              echo "" >> ARCHITECTURE.md
              # When we find the import line, output the mermaid fence and chart content
              echo '```mermaid' >> ARCHITECTURE.md
              cat chart.md >> ARCHITECTURE.md
              echo '```' >> ARCHITECTURE.md
              # Add newline after mermaid block
              echo "" >> ARCHITECTURE.md
            else
              # Output all other lines as-is
              echo "$line" >> ARCHITECTURE.md
            fi
          done < main.md
      - name: Commit changes
        run: |
          git config --local user.email "zorro.cheng@hkmci.com"
          git config --local user.name "ZorroCheng-MC"
          git add ARCHITECTURE.md
          git commit -m "Update ARCHITECTURE.md" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}