name: Generate Documentation
on:
  push:
    paths:
      - 'main.md'
      - 'chart.md'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate ARCHITECTURE.md
        shell: bash
        run: |
          # Create new ARCHITECTURE.md
          rm -f ARCHITECTURE.md
          touch ARCHITECTURE.md
          
          # Read main.md line by line and process
          while IFS= read -r line
          do
            if [[ $line == *"@import \"chart.md\""* ]]; then
              continue
            elif [[ $line == *"```mermaid"* ]]; then
              echo "```mermaid" >> ARCHITECTURE.md
              cat chart.md >> ARCHITECTURE.md
              echo "```" >> ARCHITECTURE.md
            else
              echo "$line" >> ARCHITECTURE.md
            fi
          done < main.md
      - name: Commit changes
        run: |
          git config --local user.email "zorro.cheng@hkmci.com"
          git config --local user.name "ZorroCheng-MC"
          git add ARCHITECTURE.md
          git commit -m "Update ARCHITECTURE.md" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}