name: Generate Documentation
on:
  push:
    paths:
      - 'main.md'
      - 'chart.md'

# Add these permissions
permissions:
  contents: write  # This allows the action to push changes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate ARCHITECTURE.md
        shell: bash
        run: |
          # First, copy main.md to ARCHITECTURE.md
          cp main.md ARCHITECTURE.md
          
          # Create a temporary file
          touch temp.md
          
          # Read ARCHITECTURE.md line by line
          while IFS= read -r line; do
            if [[ "$line" == *"@import \"chart.md\""* ]]; then
              cat chart.md >> temp.md
            else
              echo "$line" >> temp.md
            fi
          done < ARCHITECTURE.md
          
          # Replace ARCHITECTURE.md with the processed content
          mv temp.md ARCHITECTURE.md
      - name: Commit changes
        run: |
          git config --local user.email "zorro.cheng@hkmci.com"
          git config --local user.name "ZorroCheng-MC"
          git add ARCHITECTURE.md
          git commit -m "Update ARCHITECTURE.md" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}